services:
  app:
    build:
      context: .
    container_name: task-management-api
    ports:
      - "5001:5001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - task-management-network

  postgres:
    image: postgres:13-alpine
    container_name: task-management-db
    hostname: db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - "./infra/healthchecks:/healthchecks"
    networks:
      - task-management-network

networks:
  task-management-network:
    driver: bridge

volumes:
  postgres-data:
